import type { Metadata } from "next";
import "./globals.css";
import Navbar from "src/components/layout/Navbar";
import { getGeneralInfo } from "src/services/fetchGeneralInfo";
import { GeneralInfoType } from "src/types";
import sanityClient, { urlFor } from "sanity";
import Footer from "src/components/layout/Footer";
import { Open_Sans } from 'next/font/google'

// const roboto = Roboto({
//   weight: ['100', '300', '400', '500', '700'],
//   style: ['normal', 'italic'],
//   subsets: ['latin'],
//   display: 'swap',
// })

const openSans = Open_Sans({
  weight: ['300', '400', '500', '600', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Kode Tech",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const generalInfo: GeneralInfoType = await sanityClient.fetch(getGeneralInfo);

  const darkLogoUrl = urlFor(generalInfo.logoDark).url();
  const lightLogoUrl = urlFor(generalInfo.logoLight).url();
  const address = generalInfo.address;
  const email = generalInfo.email;
  const contactNumbers = generalInfo.contactNumbers;
  const formattedSocialLinks = generalInfo.socialLinks.map((link) => ({
    name: link.name,
    icon: link.icon,
    url: link.link || "",
  }));

  return (
    <html lang="en">
      <body className="antialiased">
        <main className={openSans.className}>
        <Navbar logo={darkLogoUrl} />
        {/* <div className="bg-animated-circuit w-full h-full min-h-screen"> */}
        {children}
        {/* </div> */}
        <Footer
          logo={lightLogoUrl}
          address={address}
          email={email}
          contactNumbers={contactNumbers}
          socialLinks={formattedSocialLinks}
        />
        </main>
      </body>
    </html>
  );
}
