import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import Navbar from "src/components/layout/Navbar";
import { getGeneralInfo } from "src/services/fetchGeneralInfo";
import { GeneralInfoType } from "src/types";
import sanityClient, { urlFor } from "sanity";
import Footer from "src/components/layout/Footer";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Kode Tech",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const generalInfo: GeneralInfoType = await sanityClient.fetch(getGeneralInfo);

  const darkLogoUrl = urlFor(generalInfo.logoDark).url();
  const lightLogoUrl = urlFor(generalInfo.logoLight).url();
  const address = generalInfo.address;
  const email = generalInfo.email;
  const contactNumbers = generalInfo.contactNumbers;
  const formattedSocialLinks = generalInfo.socialLinks.map((link) => ({
    name: link.name,
    icon: link.icon,
    url: link.link || "",
  }));

  return (
    <html lang="en">
      <body className="antialiased">
        <Navbar logo={darkLogoUrl} />
        {/* <div className="bg-animated-circuit w-full h-full min-h-screen"> */}
        {children}
        {/* </div> */}
        <Footer
          logo={lightLogoUrl}
          address={address}
          email={email}
          contactNumbers={contactNumbers}
          socialLinks={formattedSocialLinks}
        />
      </body>
    </html>
  );
}
